title: Nonconvex quantum verification
logo: /assets/img/logo.png
description: This project is support by NSF (CCF:FET:Efficient and Robust Characterization of Quantum Systems)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
